;The TashTwenty logo in the form of a 32x32 bitmap icon with mask
;................................................................
;................................................................
;................................................................
;................................................................
;................................................................
;................................................................
;................................................................
;................................................................
;............................##################..######..........
;........................######            ########  ####........
;......................####                        ######........
;....................####    ####  ##            ########........
;....................##  ######  ####  ####  ##########..........
;....................########    ##    ####  ########............
;......................######  ####    ####  ####................
;........................##    ####    ####  ####................
;........................##    ####    ####  ####................
;........................##      ##    ####  ####................
;........................##      ##  ######  ##########..........
;........................####      ########  ######  ####........
;..##########################        ######  ##    ############..
;##                        ####                  ########      ##
;##                        ########          ##########        ##
;##                          ########################          ##
;##                              ################              ##
;##                                                            ##
;##      ####                                                  ##
;##                                                            ##
;##                                                            ##
;..############################################################..
;................................................................
;................................................................
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x03
	retlw	0xFE
	retlw	0xE0
	retlw	0x00
	retlw	0x0E
	retlw	0x07
	retlw	0xB0
	retlw	0x00
	retlw	0x18
	retlw	0x00
	retlw	0x70
	retlw	0x00
	retlw	0x33
	retlw	0x40
	retlw	0xF0
	retlw	0x00
	retlw	0x2E
	retlw	0xDB
	retlw	0xE0
	retlw	0x00
	retlw	0x3C
	retlw	0x9B
	retlw	0xC0
	retlw	0x00
	retlw	0x1D
	retlw	0x9B
	retlw	0x00
	retlw	0x00
	retlw	0x09
	retlw	0x9B
	retlw	0x00
	retlw	0x00
	retlw	0x09
	retlw	0x9B
	retlw	0x00
	retlw	0x00
	retlw	0x08
	retlw	0x9B
	retlw	0x00
	retlw	0x00
	retlw	0x08
	retlw	0xBB
	retlw	0xE0
	retlw	0x00
	retlw	0x0C
	retlw	0x7B
	retlw	0xB0
	retlw	0x7F
	retlw	0xFC
	retlw	0x3A
	retlw	0x7E
	retlw	0x80
	retlw	0x06
	retlw	0x00
	retlw	0xF1
	retlw	0x80
	retlw	0x07
	retlw	0x83
	retlw	0xE1
	retlw	0x80
	retlw	0x03
	retlw	0xFF
	retlw	0xC1
	retlw	0x80
	retlw	0x00
	retlw	0xFF
	retlw	0x01
	retlw	0x80
	retlw	0x00
	retlw	0x00
	retlw	0x01
	retlw	0x8C
	retlw	0x00
	retlw	0x00
	retlw	0x01
	retlw	0x80
	retlw	0x00
	retlw	0x00
	retlw	0x01
	retlw	0x80
	retlw	0x00
	retlw	0x00
	retlw	0x01
	retlw	0x7F
	retlw	0xFF
	retlw	0xFF
	retlw	0xFE
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x03
	retlw	0xFE
	retlw	0xE0
	retlw	0x00
	retlw	0x0F
	retlw	0xFF
	retlw	0xF0
	retlw	0x00
	retlw	0x1F
	retlw	0xFF
	retlw	0xF0
	retlw	0x00
	retlw	0x3F
	retlw	0xFF
	retlw	0xF0
	retlw	0x00
	retlw	0x3F
	retlw	0xFF
	retlw	0xE0
	retlw	0x00
	retlw	0x3F
	retlw	0xFF
	retlw	0xC0
	retlw	0x00
	retlw	0x1F
	retlw	0xFF
	retlw	0x00
	retlw	0x00
	retlw	0x0F
	retlw	0xFF
	retlw	0x00
	retlw	0x00
	retlw	0x0F
	retlw	0xFF
	retlw	0x00
	retlw	0x00
	retlw	0x0F
	retlw	0xFF
	retlw	0x00
	retlw	0x00
	retlw	0x0F
	retlw	0xFF
	retlw	0xE0
	retlw	0x00
	retlw	0x0F
	retlw	0xFF
	retlw	0xF0
	retlw	0x7F
	retlw	0xFF
	retlw	0xFF
	retlw	0xFE
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0xFF
	retlw	0x7F
	retlw	0xFF
	retlw	0xFF
	retlw	0xFE
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
	retlw	0x00
